language: ruby

sudo: false

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head

before_install: gem install bundler

bundler_args: --without debug --jobs=3 --retry=3 --path=../vendor/bundle

cache: bundler

addons:
  code_climate:
    repo_token: f86575690ba75e81107a310a79ec158a4dbac013cd17c46dcb97c2dfae817fcc

script: bundle exec rake && bundle exec codeclimate-test-reporter
